AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: The account API for Popcorn Cloud

Globals:
  Function:
    MemorySize: 1769
    Architectures:
      - arm64
    Runtime: nodejs20.x
    Timeout: 30
    Tracing: Active
    Environment:
      Variables:
        TABLE_NAME: !Ref AccountTable

Resources:
  AccountTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: popcorn-cloud.account
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: Sub
          AttributeType: S
        - AttributeName: Email
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: SubIndex
          KeySchema:
            - AttributeName: Sub
              KeyType: HASH
            - AttributeName: PK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: EmailIndex
          KeySchema:
            - AttributeName: Email
              KeyType: HASH
            - AttributeName: PK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
      TimeToLiveSpecification:
        AttributeName: TTL
        Enabled: true
  AccountApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Cors:
        AllowOrigin: "'http://localhost:8001'"
        AllowHeaders: "'*'"
        AllowMethods: "'*'"
        AllowCredentials: "'true'"
      Auth:
        DefaultAuthorizer: ApiAuthorizer
        AddDefaultAuthorizerToCorsPreflight: false
        Authorizers:
          ApiAuthorizer:
            FunctionArn:
              Fn::ImportValue: ApiAuthorizerFunctionArn
            Identity:
              Header: Authorization
              ValidationExpression: '.*'
  AccountFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: dist/index.handler
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref AccountApi
            Path: /{proxy+}
            Method: ANY
      Policies:
        - DynamoDBCrudPolicy:
            TableName:
              !Ref AccountTable
        - AmazonSESFullAccess
    Metadata:
      BuildMethod: makefile
