AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: OpenIddit Serverless Demo

Globals:
  Function:
    MemorySize: 1769
    Architectures:
      - arm64
    Runtime: dotnet8
    Timeout: 30
    Tracing: Active
    Environment:
      Variables:
        TABLE_NAME: openiddict-serverless-demo.openiddict

Resources:
  OpenIddictApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Cors:
        AllowOrigin: "'http://localhost:8001'"
        AllowHeaders: "'*'"
        AllowMethods: "'*'"
        AllowCredentials: "'true'"
  OpenIddictFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/OpenIddictServerlessDemo
      Handler: OpenIddictServerlessDemo
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref OpenIddictApi
            Path: /{proxy+}
            Method: ANY
      Policies:
        - DynamoDBCrudPolicy:
            TableName:
              Fn::Sub: arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/openiddict-serverless-demo.openiddict
        - AmazonSESFullAccess
    Metadata:
      BuildMethod: makefile
