AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: OpenIddit Serverless Demo

Globals:
  Function:
    MemorySize: 1769
    Architectures:
      - arm64
    Runtime: dotnet8
    Timeout: 30
    Tracing: Active
    Environment:
      Variables:
        TABLE_NAME: openiddict-serverless-demo.openiddict
        ASPNETCORE_ENVIRONMENT: Production

Resources:
  OpenIddictApi:
    Type: AWS::Serverless::HttpApi
  OpenIddictFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/OpenIddictServerlessDemo
      Handler: OpenIddictServerlessDemo::OpenIddictServerlessDemo.LambdaEntryPoint::FunctionHandlerAsync
      Events:
        Api:
          Type: HttpApi
          Properties:
            ApiId: !Ref OpenIddictApi
            Path: /{proxy+}
            Method: ANY
      Policies:
        - DynamoDBCrudPolicy:
            TableName:
              Fn::Sub: arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/openiddict-serverless-demo.openiddict
        - Statement:
          - Effect: Allow
            Action:
              - ssm:GetParametersByPath
            Resource: 
              - Fn::Sub: arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/OpenIddictServerlessDemo/Certificates
          - Effect: Allow
            Action:
              - ssm:PutParameter
              - ssm:GetParameter
              - ssm:DescribeParameters
              - ssm:GetParametersByPath
            Resource: 
              - Fn::Sub: arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/OpenIddictServerlessDemo/DataProtection/
          - Effect: Allow
            Action:
              - dynamodb:Query
            Resource:
              - Fn::Sub: arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/openiddict-serverless-demo.openiddict/index/*
          # Needed for setup script, should not be run during startup in production
          - Effect: Allow
            Action:
              - dynamodb:ListTables
            Resource: "*"
          - Effect: Allow
            Action:
              - dynamodb:DescribeTable
              - dynamodb:DescribeTimeToLive
            Resource:
              - Fn::Sub: arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/openiddict-serverless-demo.openiddict
    Metadata:
      BuildMethod: makefile
